title: "Portfolio"
author: "Andreas Winther Sorman"
description: "My Portfolio"
baseurl: /
url: "http://www.andreaswinthersorman.com/"

# Jekyll settings
permalink: /:title/          # see https://jekyllrb.com/docs/permalinks/
excerpt_separator: "\n\n\n"  # indicates the end of the excerpt by two blank lines

# Page settings
show_excerpts: false          # show article previews on the home page instead of headlines
hide_title: true            # remove site heading in the header
post_footer: true            # show previous and next links at the end of each post
date_format: ""              # see http://shopify.github.io/liquid/filters/date/

# Theme settings
style: minimal               # choose between "default", "contrast" and "minimal"
dark_theme: true            # enables dark mode

navigation:                  # (optional) site navigation in the header
  - index.html
  - archive.md
  - oddbox.md
  - about.md

icons:                       # (optional) icons in the header, see http://fontawesome.com/icons
  envelope: "mailto:wianso98@gmail.com"
  github: "https://github.com/VortexCoyote"
  linkedin: "https://www.linkedin.com/in/andreas-winther-sorman-b49065b5/"
  # rss: "/feed.xml"

comments:                    # embed disqus or isso comments
#  disqus: ""
#  isso: ""

plugins: 
 - jekyll-feed
 - jekyll-paginate
 - jekyll-default-layout